### ISSUE TITLE
Content field is no longer required

### ISSUE THREAD

**Issue by ramesh-dada** [clarkwinkelmann/flarum-ext-first-post-approval#1] opened 2021-06-07 14:20 UTC
This literally break the flarum built-in content field and may be dangerous as users are then allowed to post without approval.

### To Reproduce:
1. Log IN 
2. Make a Discussion and leave content field blank It will show Oops something went wrong instead of content is required.
3. **Do not** Click post more than one time just refresh you will see that discussion is posted without approval and without content.

### How it can be dangerous?
Users can abuse in title only!!

**Comment by clarkwinkelmann** [comment] 2021-06-07 14:54
I am not able to reproduce.

Can you share your `php flarum info` output?

Do you require primary or secondary tags to be selected? Did you select tags for the bug to be reproducible?

"Oops something went wrong" refers to either a server 500 error or a javascript error. Can you check the Flarum log at `<flarum>/storage/logs` and your browser javascript console for an error message? I don't see an error message when I try reproducing, I see the expected "The content field is required" validation error.

And finally does the error go away when First Post Approval is disabled? I have a hard time figuring out how this extension could affect which fields are required in Flarum.

EDIT: could it be an instance of https://github.com/flarum/core/issues/1767 ? I believe you are the one who also replied on the recent discussion about this on Discuss? If it's indeed that issue then let me know and I'll close this one.

**Comment by ramesh-dada** [comment] 2021-06-08 04:06
Make sure you are on v1.0.2

No, I am not talking about this flarum/core#1767 bug, To reproduce just enter title and tags do not touch content field and click post discussion in v1.0.2 then you will see that It will show you console error and OOps Something went wrong, and The discussion will be posted to see refresh the page, and The above flarum/core#1767 bug causes user avatar shown it is white space but this is different It doesn't even require user to post.. and also Bypasses the approval requirement and may be dangerous.

**Comment by clarkwinkelmann** [comment] 2021-06-08 17:36
please copy the full error message from the Flarum log file or browser javascript console as described above and provide your `php flarum info` output

**Comment by ramesh-dada** [comment] 2021-06-09 14:42
OH @clarkwinkelmann I am really very very sorry I realized that when using your extension with FOF Filter causes this and I am unable to say who to say clark's extension is buggy or FOF's extension is buggy as when I disable yours nothing happens and when I disable Fof's and enable yours then also nothing happens, But when I enable them both then this error occurs See the below console error!

![image](https://user-images.githubusercontent.com/75124237/121376177-efaaf780-c95e-11eb-9f70-9d9ec7b48116.png)

**Comment by clarkwinkelmann** [comment] 2021-06-09 15:06
Thanks, that's helpful to know :+1: 

Can you share the error from the Flarum log file at `<flarum>/storage/logs` please? Without that error message I can't investigate anything.

**Comment by ramesh-dada** [comment] 2021-06-11 11:36
@clarkwinkelmann I am really sorry 😔 I can't as I removed this extension and Today only I cleaned my localhost, According to me now you can also reproduce this all you need to do is turn on both extensions and post without touching content field, maybe I can give you error.log after few days.

**Comment by clarkwinkelmann** [comment] 2021-06-11 20:10
No worries. I never tried to use the two extensions together and don't have much time to test it.

I'll close this for now but if you try again in the future feel free to share the logs and I'll re-open to take a look.

The logs help because I can get an idea of what's wrong (and in particular, whether it's this extension or the other one that's responsible) without having to download anything.

**Closed as completed by clarkwinkelmann** 2021-06-11 20:10 UTC

**Comment by ramesh-dada** [comment] 2021-06-12 07:38
I am sorry to say this, I think you should not close it as It is a issue in this extension still and If you are not looking into it no problem I will share you logs later but this is **BUG** and isn't yet fixed.

**Comment by clarkwinkelmann** [comment] 2021-06-14 21:23
Unfortunately I don't have the time to go and test the compatibility with the other extensions myself. If I keep this open now, it will likely stay open forever as an unconfirmed issue without any more chance of being fixed.

If I see an error message that makes it clear this extension has an issue, I'll make sure to take a look when I find some time.
